package com.grasia.prima.ppi.api.constant;

import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
public enum GlobalMessage {
    SUCCESS(HttpStatus.OK, Constant.SUCCESS),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, Constant.UNAUTHORIZED),
    DATA_NOT_FOUND(HttpStatus.BAD_REQUEST, Constant.DATA_NOT_FOUND),
    WRONG_USERNAME_OR_PASSWORD(HttpStatus.BAD_REQUEST, Constant.WRONG_USERNAME_OR_PASSWORD),
    REFRESH_TOKEN_NOT_VALID(HttpStatus.BAD_REQUEST, Constant.REFRESH_TOKEN_NOT_VALID),
    USERNAME_HAS_BEEN_REGISTERED(HttpStatus.BAD_REQUEST, Constant.USERNAME_HAS_BEEN_REGISTERED),
    EMAIL_HAS_BEEN_REGISTERED(HttpStatus.BAD_REQUEST, Constant.EMAIL_HAS_BEEN_REGISTERED),
    MIN_PASSWORD_LENGTH(HttpStatus.BAD_REQUEST, Constant.MIN_PASSWORD),
    MUST_CONTAIN_UPPER_CASE(HttpStatus.BAD_REQUEST, Constant.MUST_CONTAIN_UPPER_CASE),
    MUST_CONTAIN_NUMBER(HttpStatus.BAD_REQUEST, Constant.MUST_CONTAIN_NUMBER),
    PASSWORD_CONFIRM_NOT_EQUALS(HttpStatus.BAD_REQUEST, Constant.PASSWORD_CONFIRM_NOT_EQUALS),
    SEQUENCE_MUST_GREATER_THAN_ZERO(HttpStatus.BAD_REQUEST, Constant.SEQUENCE_MUST_GREATER_THAN_ZERO),
    MENU_SEQUENCE_HAS_BEEN_REGISTERED(HttpStatus.BAD_REQUEST, Constant.MENU_SEQUENCE_HAS_BEEN_REGISTERED),
    SUB_MENU_SEQUENCE_HAS_BEEN_REGISTERED(HttpStatus.BAD_REQUEST, Constant.SUB_MENU_SEQUENCE_HAS_BEEN_REGISTERED),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, Constant.INTERNAL_SERVER_ERROR);

    public final HttpStatus status;
    public final String message;
}
